# just is a command runner, Justfile is very similar to Makefile, but simpler.
set default-list := true

# Run backend (Rust) integration tests
[group('test')]
test-be: gen-icons
  cargo test --all-features

# Run frontend unit tests
[group('test')]
test-fe:
  pnpm test

# Run every local Android plugin's Robolectric/JVM unit tests via the aggregated
# `testPlugins` gradle task. Skipped unless tauri.settings.gradle exists; fails if
# it is stale (wrong repo root) or omits any local path plugin from Cargo.toml —
# both would silently skip a plugin's tests, the failure mode this gate exists to
# prevent. tauri.settings.gradle is gitignored, generated by `tauri android build/dev`.
[group('test')]
test-plugin:
  @f=src-tauri/gen/android/tauri.settings.gradle; \
  if [ ! -f "$f" ]; then \
    echo "test-plugin: skipped (run 'just android-debug' once to enable — tauri.settings.gradle is gitignored, generated by tauri android build/dev)"; \
  else \
    if ! grep -qF "$PWD" "$f"; then \
      echo "test-plugin: $f is stale (doesn't reference the current repo root); run 'just android-debug' to regenerate." >&2; exit 1; \
    fi; \
    missing=""; \
    for p in $(grep -oE 'tauri-plugin-[a-z0-9_-]+ = \{' src-tauri/Cargo.toml | grep -oE 'tauri-plugin-[a-z0-9_-]+'); do \
      grep -q ":$p'" "$f" || missing="$missing $p"; \
    done; \
    if [ -n "$missing" ]; then \
      echo "test-plugin: missing from $f:$missing (stale generation — run 'just android-debug' so these plugins' tests actually run)" >&2; exit 1; \
    fi; \
    cd src-tauri/gen/android && ./gradlew testPlugins --console=plain; \
  fi

# Run all tests (backend + frontend + plugin)
[group('test')]
test: test-be test-fe test-plugin

# Clippy + vue-tsc type check
lint: gen-icons
  cargo clippy --all-targets --all-features -- -D warnings
  pnpm exec vue-tsc --noEmit

# Format Rust + Vue code
fmt:
  cargo fmt
  prettier --write .

# Refresh the embedded Mozilla CA bundle (rustpass/data/cacert.pem) that backs
# HTTPS git certificate verification on Android. Run once per release so the
# trusted roots track Mozilla's trust decisions, then commit the file.
refresh-ca:
  curl -fsSL https://curl.se/ca/cacert.pem -o rustpass/data/cacert.pem
  @echo "Refreshed rustpass/data/cacert.pem — run 'just test' (bundle validity check), then commit."

# Desktop dev server with hot reload
dev: gen-icons
  pnpm tauri dev

# Build debug APK (optional: specify arch e.g. aarch64, armv7, i686, x86_64; builds universal if omitted)
[group('android')]
android-debug target='': gen-icons
  @if [ -z "{{ target }}" ]; then \
    pnpm tauri android build --debug; \
  else \
    pnpm tauri android build --debug -t "{{ target }}"; \
  fi

# Build release APKs (per-arch + universal, signed if keystore.properties exists)
[group('android')]
android-release: gen-icons
  pnpm tauri android build --apk --split-per-abi
  pnpm tauri android build --apk

# Android dev server (requires connected device or emulator)
[group('android')]
android-dev: gen-icons
  pnpm tauri android dev

# Fast Kotlin compile gate (seconds, no NDK/Rust cross-compile needed).
# Catches compile errors in src-tauri/gen/android/app/src/main/java/**/*.kt before the full build.
# Requires a prior `pnpm tauri android *` run so tauri.settings.gradle points at a real cargo registry.
# If it errors with "project ':tauri-android' directory does not exist", run `just android-debug` once to regenerate.
[group('android')]
kotlin-check:
  @test -f src-tauri/gen/android/tauri.settings.gradle || { \
    echo "kotlin-check: tauri.settings.gradle is missing (gitignored; generated by 'tauri android build/dev')." >&2; \
    echo "  Run 'just android-debug' or 'just android-dev' once to generate it, then retry." >&2; \
    exit 1; \
  }
  cd src-tauri/gen/android && ./gradlew :app:compileUniversalDebugKotlin --console=plain

# Install debug APK to connected device (auto-detects arch, or specify e.g. aarch64)
[group('android')]
android-install target='': gen-icons
  @if [ -z "{{ target }}" ]; then \
    ABI=$$(adb shell getprop ro.product.cpu.abi 2>/dev/null); \
    case "$$ABI" in \
      arm64-v8a)   T="aarch64" ;; \
      armeabi-v7a) T="armv7" ;; \
      x86_64)      T="x86_64" ;; \
      x86)         T="i686" ;; \
      *)           T="aarch64" ;; \
    esac; \
    echo "Detected ABI: $${ABI:-unknown}, target: $$T"; \
    pnpm tauri android build --debug -t "$$T"; \
  else \
    pnpm tauri android build --debug -t "{{ target }}"; \
  fi
  adb install src-tauri/gen/android/app/build/outputs/apk/universal/debug/app-universal-debug.apk

# Install release APK to connected device (auto-detect arch)
[group('android')]
android-install-release: android-release
  @ARCH=$$(adb shell getprop ro.product.cpu.abi 2>/dev/null); \
  case "$$ARCH" in \
    arm64-v8a)   APK="arm64/release/app-arm64-release.apk" ;; \
    armeabi-v7a) APK="arm/release/app-arm-release.apk" ;; \
    x86_64)      APK="x86_64/release/app-x86_64-release.apk" ;; \
    x86)         APK="x86/release/app-x86-release.apk" ;; \
    *)           APK="universal/release/app-universal-release.apk" ;; \
  esac; \
  echo "Installing for ABI: $${ARCH:-unknown}"; \
  adb install "src-tauri/gen/android/app/build/outputs/apk/$$APK"

# Bump version, commit, and tag for release
release new_version:
  ./scripts/bump-version.sh {{new_version}}
  git add Cargo.toml Cargo.lock package.json src-tauri/tauri.conf.json CHANGELOG.md
  git commit -m "build: release v{{new_version}}"
  git tag "v{{new_version}}" -m "build: release v{{new_version}}"

# Regenerate app icons + web favicons if source is newer
[private]
gen-icons:
  ./scripts/gen-icons.sh
