// SPDX-FileCopyrightText: 2026 Zexin Yuan <gpm@yzx9.xyz>
//
// SPDX-License-Identifier: MIT OR Apache-2.0

//! R085 codegen: emit checked-in TypeScript mirrors of the Rust IPC enums.
//!
//! The single source of truth is the Rust enums themselves, via `ts-rs` (which
//! reads their existing serde attributes). `just gen-codegen` regenerates
//! `app/src/api/generated/`; `just lint` runs this binary with `--check` so a
//! stale checked-in file fails the gate. Adding or renaming a Rust variant
//! without regenerating turns the lint red — closing the silent Rust↔TS
//! rename-drift hole.

use std::fs;
use std::path::PathBuf;
use std::process::ExitCode;

use gpm_lib::{BackgroundSyncCadence, GateIdle, SecureScreenMode};
use rustpass::identity::IdentityType;
use rustpass::{CommitSigStatus, LockMode, VerifyMode};
use tauri_plugin_keystore::BiometricState;
use ts_rs::{Config, ExportError, TS};

/// Prefix every generated file carries (SPDX + `@generated` marker).
const HEADER: &str = "\
// SPDX-FileCopyrightText: 2026 Zexin Yuan <gpm@yzx9.xyz>
//
// SPDX-License-Identifier: MIT OR Apache-2.0
// @generated by `just gen-codegen` (`cargo run -p codegen`) from Rust enums via
// ts-rs. Do not edit; regenerate instead. Source: ";

fn main() -> ExitCode {
    let check = std::env::args().any(|a| a == "--check");
    let cfg = Config::default();
    let dir = workspace_root().join("app/src/api/generated");

    let files: &[(&str, String, &str)] = &[
        ("rustpass.ts", gen_rustpass(&cfg), "crates/rustpass"),
        (
            "keystore.ts",
            gen_keystore(&cfg),
            "crates/tauri-plugin-keystore",
        ),
        ("app.ts", gen_app(&cfg), "app/src-tauri"),
    ];

    let mut stale = false;
    for (name, body, source) in files {
        let path = dir.join(name);
        let content = format!("{HEADER}{source}\n\n{body}\n");
        if check {
            match fs::read_to_string(&path) {
                Ok(existing) if existing == content => {}
                _ => {
                    stale = true;
                    eprintln!(
                        "codegen: {} is stale or missing (source: {source}); run `just gen-codegen`",
                        path.display()
                    );
                }
            }
        } else {
            fs::create_dir_all(&dir).expect("create generated dir");
            fs::write(&path, content).expect("write generated file");
            println!("wrote {}", path.display());
        }
    }

    if stale {
        ExitCode::FAILURE
    } else {
        ExitCode::SUCCESS
    }
}

/// Workspace root = two levels up from this crate (`crates/codegen` → root),
/// resolved at compile time so generation is independent of the invocation cwd.
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Strip ts-rs's per-type `// This file was generated by ts-rs…` header and the
/// blank line after it, so a grouped file carries only the file-level header.
fn strip_ts_header(s: &str) -> String {
    s.lines()
        .skip_while(|line| {
            let t = line.trim();
            t.starts_with("//") || t.is_empty()
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Unwrap each `export_to_string` result, strip its ts-rs header, and join the
/// declarations with blank lines.
fn join_exports<const N: usize>(results: [Result<String, ExportError>; N]) -> String {
    results
        .into_iter()
        .map(|r| strip_ts_header(&r.expect("ts-rs export_to_string failed")))
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn gen_rustpass(cfg: &Config) -> String {
    join_exports([
        VerifyMode::export_to_string(cfg),
        LockMode::export_to_string(cfg),
        CommitSigStatus::export_to_string(cfg),
        IdentityType::export_to_string(cfg),
    ])
}

fn gen_keystore(cfg: &Config) -> String {
    join_exports([BiometricState::export_to_string(cfg)])
}

fn gen_app(cfg: &Config) -> String {
    join_exports([
        SecureScreenMode::export_to_string(cfg),
        BackgroundSyncCadence::export_to_string(cfg),
        GateIdle::export_to_string(cfg),
    ])
}

#[cfg(test)]
mod tests {
    use super::strip_ts_header;

    #[test]
    fn strip_ts_header_drops_leading_line_comments_and_blanks() {
        let input = "// This file was generated by ts-rs.\n\n/** doc */\nexport type X = \"a\";";
        assert_eq!(strip_ts_header(input), "/** doc */\nexport type X = \"a\";",);
    }

    #[test]
    fn strip_ts_header_passes_through_when_no_header() {
        let input = "/** doc */\nexport type X = \"a\";";
        assert_eq!(strip_ts_header(input), input);
    }
}
