// SPDX-FileCopyrightText: 2026 Zexin Yuan <gpm@yzx9.xyz>
//
// SPDX-License-Identifier: Apache-2.0

// Data + pure helpers for the About page (Overview / Acknowledgements /
// Licenses tabs). The license inventory is a build-time artifact
// (`public/licenses.json`, generated by scripts/gen-licenses.mjs) fetched
// lazily only when the Licenses tab is opened — it is never part of the app's
// initial payload.

/** A single dependency and its license. Mirrors the generator's JSON shape. */
export interface LicensePackage {
  ecosystem: "rust" | "npm";
  name: string;
  version: string;
  /** SPDX expression (e.g. "MIT OR Apache-2.0") or "UNKNOWN". */
  license: string;
  repository: string;
  /** Full license text; "" when unavailable (degraded build). */
  licenseText: string;
}

/** The full license-inventory document. */
export interface LicensesData {
  /** Always null today (the generator keeps the artifact deterministic). */
  generatedAt: string | null;
  /** False when any source was skipped/degraded (e.g. cargo missing). */
  complete: boolean;
  /** Human-readable caveat; "" when fully complete. */
  note: string;
  /** Per-ecosystem package counts. */
  ecosystems: Record<string, number>;
  packages: LicensePackage[];
}

/**
 * A hand-curated entry for the Acknowledgements tab — the projects gpm leans
 * on most. `descKey` resolves through the `about` i18n bundle so each is
 * translated for the active locale.
 */
export interface Acknowledgement {
  id: string;
  name: string;
  url: string;
  license: string;
  /** i18n key suffix under `about.ack.<id>`. */
  descKey: string;
}

/**
 * gpm's design north stars, shown on the Overview tab. Each `goalKey` resolves
 * to a one-line statement in the `about` bundle.
 */
export const DESIGN_GOALS: readonly string[] = [
  "ageOnly",
  "androidFirst",
  "gitSync",
  "gopassCompatible",
  "securityFirst",
] as const;

/**
 * The headline open-source projects gpm builds on and is inspired by. Ordered
 * roughly by how central each is to gpm's existence — gopass (the conceptual
 * ancestor) first.
 */
export const ACKNOWLEDGEMENTS: readonly Acknowledgement[] = [
  {
    id: "gopass",
    name: "gopass",
    url: "https://www.gopass.pw/",
    license: "MIT",
    descKey: "about.ack.gopass.desc",
  },
  {
    id: "age",
    name: "age / rage",
    url: "https://github.com/str4d/rage",
    license: "MIT OR Apache-2.0",
    descKey: "about.ack.age.desc",
  },
  {
    id: "tauri",
    name: "Tauri",
    url: "https://tauri.app/",
    license: "MIT OR Apache-2.0",
    descKey: "about.ack.tauri.desc",
  },
  {
    id: "vue",
    name: "Vue.js",
    url: "https://vuejs.org/",
    license: "MIT",
    descKey: "about.ack.vue.desc",
  },
  {
    id: "git2",
    name: "git2 / libgit2",
    url: "https://github.com/libgit2/git2-rs",
    license: "MIT OR Apache-2.0",
    descKey: "about.ack.git2.desc",
  },
  {
    id: "rpgp",
    name: "rpgp",
    url: "https://github.com/rpgp/rpgp",
    license: "MIT OR Apache-2.0",
    descKey: "about.ack.rpgp.desc",
  },
  {
    id: "nucleo",
    name: "nucleo",
    url: "https://github.com/helix-editor/nucleo",
    license: "MPL-2.0",
    descKey: "about.ack.nucleo.desc",
  },
] as const;

// ── License-inventory fetch (lazy, cached, failure-tolerant) ────────────────

let cache: Promise<LicensesData> | null = null;

/**
 * Test-only seam to drop the session cache between tests. Production code never
 * resets — the inventory is fetched once per session.
 * @internal
 */
export function __resetLicensesCacheForTests(): void {
  cache = null;
}

/**
 * Fetch the license inventory once per session. Resolves to a degraded
 * (empty-packages) document on any failure so the UI always has a typed shape
 * to render — the Licenses tab shows its "unavailable" state from
 * `data.complete` / `data.packages.length`, never a thrown exception.
 */
export function fetchLicenses(): Promise<LicensesData> {
  if (!cache) {
    const url = `${import.meta.env.BASE_URL}licenses.json`;
    cache = fetch(url)
      .then((r) => {
        if (!r.ok) throw new Error(`licenses.json HTTP ${r.status}`);
        return r.json() as Promise<LicensesData>;
      })
      .catch((e): LicensesData => {
        // Don't cache the failure forever — a retry (page re-mount) should try
        // again, since the vite plugin may have just written the file.
        cache = null;
        return {
          generatedAt: null,
          complete: false,
          note: String(e?.message ?? e),
          ecosystems: {},
          packages: [],
        };
      });
  }
  return cache;
}

// ── Pure grouping + filtering helpers (unit-tested) ─────────────────────────

/** A license group: all packages sharing one SPDX expression. */
export interface LicenseGroup {
  license: string;
  count: number;
  packages: LicensePackage[];
}

/**
 * Group packages by SPDX expression, most-populous first (then alphabetically).
 * The vast majority of deps share a handful of expressions (mostly
 * "MIT OR Apache-2.0"), so this collapses hundreds of packages into ~8-15
 * collapsible rows — the UI's primary scale-control.
 */
export function groupLicenses(
  packages: readonly LicensePackage[],
): LicenseGroup[] {
  const map = new Map<string, LicensePackage[]>();
  for (const p of packages) {
    const key = p.license || "UNKNOWN";
    let arr = map.get(key);
    if (!arr) {
      arr = [];
      map.set(key, arr);
    }
    arr.push(p);
  }
  return [...map.entries()]
    .map(([license, pkgs]) => ({
      license,
      count: pkgs.length,
      // Stable sub-ordering: ecosystem, then name, then version.
      packages: pkgs
        .slice()
        .sort((a, b) =>
          a.ecosystem !== b.ecosystem
            ? a.ecosystem < b.ecosystem
              ? -1
              : 1
            : a.name !== b.name
              ? a.name < b.name
                ? -1
                : 1
              : a.version < b.version
                ? -1
                : a.version > b.version
                  ? 1
                  : 0,
        ),
    }))
    .sort((a, b) =>
      b.count !== a.count ? b.count - a.count : a.license < b.license ? -1 : 1,
    );
}

/**
 * Case-insensitive substring match across name (and license, so a search for
 * "apache" finds every Apache-licensed dep). Used for the Licenses-tab search
 * box; returns packages in display order.
 */
export function filterPackages(
  packages: readonly LicensePackage[],
  query: string,
): LicensePackage[] {
  const q = query.trim().toLowerCase();
  if (!q) return packages.slice();
  return packages.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.license.toLowerCase().includes(q) ||
      p.version.toLowerCase().includes(q),
  );
}
