// SPDX-FileCopyrightText: 2026 Zexin Yuan <gpm@yzx9.xyz>
//
// SPDX-License-Identifier: Apache-2.0

#![allow(missing_docs)]

// The Kotlin @Command method names (snake_cased). The plugin is backend-only
// (Rust invokes via PluginHandle, never from the WebView), so these scope only
// the autogenerated permission TOMLs. Mirrors biometric-keystore's surface.
const COMMANDS: &[&str] = &[
    "is_biometric_available",
    "alias_state",
    "store",
    "retrieve",
    "delete",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
