#!/usr/bin/env sh
# SPDX-FileCopyrightText: 2026 Zexin Yuan <gpm@yzx9.xyz>
#
# SPDX-License-Identifier: Apache-2.0

# Regenerate Tauri's native app icons (src-tauri/icons/) and the web favicon
# sizes (public/icon-*.png) from the single source assets/app-icon.png.
#
# Each step only runs when its output is older than the source, so this is
# safe to invoke on every dev/lint/test/build run without needless churn.
# Idempotent. POSIX sh.

set -eu

SRC=assets/app-icon.png

# Native icons — regenerated by `tauri icon` when stale.
[ src-tauri/icons/128x128.png -nt "$SRC" ] || pnpm tauri icon "$SRC"

# Web favicon sizes — copied from the set `tauri icon` just produced.
# Re-sync only when the source changed, to avoid triggering Vite reloads.
if [ ! -f public/icon-512.png ] || [ public/icon-512.png -ot "$SRC" ]; then
  cp src-tauri/icons/32x32.png      public/icon-32.png
  cp src-tauri/icons/64x64.png      public/icon-64.png
  cp src-tauri/icons/128x128.png    public/icon-128.png
  cp src-tauri/icons/128x128@2x.png public/icon-256.png
  cp src-tauri/icons/icon.png       public/icon-512.png
fi
