// SPDX-FileCopyrightText: 2026 Zexin Yuan <gpm@yzx9.xyz>
//
// SPDX-License-Identifier: Apache-2.0

#![allow(missing_docs)]

// The Kotlin @Command method names (snake_cased). `has_stored` is composed in
// Rust from `alias_state` (no Kotlin command), so it is NOT listed. The plugin
// is backend-only (Rust invokes via PluginHandle, never from the WebView), so
// these scope only the autogenerated permission TOMLs.
const COMMANDS: &[&str] = &[
    "is_biometric_available",
    "open_security_settings",
    "alias_state",
    "store",
    "retrieve",
    "delete",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
