name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup CI environment
        uses: ./.github/actions/setup-ci-env

      - name: Check Rust formatting
        run: nix develop --accept-flake-config --command sh -c 'cargo fmt --check'

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup CI environment
        uses: ./.github/actions/setup-ci-env
        with:
          pnpm_cache: true

      - name: Check frontend formatting
        run: nix develop --accept-flake-config --command sh -c 'pnpm install --frozen-lockfile && pnpm exec prettier --check .'

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup CI environment
        uses: ./.github/actions/setup-ci-env

      - name: Check Nix formatting
        run: nix develop --accept-flake-config --command sh -c 'nixfmt --check $(git ls-files "*.nix")'
