name: Release Android APK

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    uses: ./.github/workflows/_build-android.yml
    with:
      build_type: release
      create_release: true
      split_per_abi: true
    secrets: inherit
